'use client';
import type {ThermalEvent,Alert} from '../../lib/api';
import type {ReviewCandidate} from '../../lib/reviewCandidates';
import {completeness,display,finite,timeline,lineage,freshness} from '../../lib/derived/intelligence';
import {RiskBadge} from '../StatusBadge';
import {StatRow} from '../UI';
export default function EventIntelligence({event:e,alerts,review}:{event:ThermalEvent;alerts:Alert[];review?:ReviewCandidate}){
 const quality=completeness(e);const confidence=e.classification?.classification_confidence;
 return <div className="intelligence-grid"><section className="review-card"><h2>Classification and evidence</h2><StatRow label="Event" value={e.id}/><StatRow label="Data mode" value={e.is_demo?'DEMO':'REAL'}/><StatRow label="ML classification" value={display(e.classification?.predicted_class)}/><StatRow label="Model confidence" value={finite(confidence)?`${Math.round(confidence*100)}%`:'Unavailable'}/><p>Confidence is the model output for this class, not a guarantee of correctness or evidence completeness.</p><StatRow label="UI evidence completeness" value={`${quality.available}/${quality.total} checks · ${quality.percent}%`}/><p>Equal-weight presence checks only; not an authoritative quality or model score.</p><ul>{quality.checks.map(([name,ok])=><li key={name}>{name}: {ok?'Available':'Missing'}</li>)}</ul><StatRow label="Model / feature version" value={`${display(e.classification?.model_version)} / ${display(e.classification?.feature_version)}`}/><h3>Why this classification?</h3><p>{e.classification?.reason||'No event-specific model explanation supplied.'}</p><p>SHAP, causal feature contributions, and explicit supporting/contradicting evidence judgments are unavailable. The measurements below are observations, not inferred feature attribution.</p>{Object.entries(e.classification?.class_probabilities||{}).map(([label,p])=><StatRow key={label} label={label.replaceAll('_',' ')} value={finite(p)?`${(p*100).toFixed(1)}%`:'Unavailable'}/>)}</section>
 <section className="review-card"><h2>Thermal facts and provenance</h2>{[['Mean FRP (MW)',e.mean_frp],['Maximum FRP (MW)',e.max_frp],['Mean brightness',e.mean_brightness],['Detections',e.detection_count],['Persistence (days)',e.persistence_days],['Spread (km)',e.spatial_spread_km],['Night fraction',e.night_fraction],['Satellite count',e.sensor_summary?.unique_satellite_count],['Instrument count',e.sensor_summary?.unique_instrument_count],['VIIRS SNPP',e.sensor_summary?.viirs_snpp_count],['VIIRS NOAA-20',e.sensor_summary?.viirs_noaa20_count],['VIIRS NOAA-21',e.sensor_summary?.viirs_noaa21_count],['MODIS',e.sensor_summary?.modis_count],['Independent detections',e.sensor_summary?.independent_detection_count],['NRT/SP representation count',e.sensor_summary?.nrt_sp_representation_count],['Day detection fraction',e.sensor_summary?.day_detection_fraction],['Night detection fraction',e.sensor_summary?.night_detection_fraction],['Cross-sensor confirmed',e.sensor_summary?.cross_sensor_confirmed]].map(([label,value])=><StatRow key={String(label)} label={String(label)} value={display(value)}/>)}<h3>Source counts · NRT/SP as reported</h3>{Object.keys(e.source_counts||{}).length?Object.entries(e.source_counts!).map(([source,count])=><StatRow key={source} label={source} value={count}/>):<p>Source-specific counts unavailable for SNPP, NOAA-20, NOAA-21 and MODIS.</p>}<h3>Historical baseline</h3><StatRow label="Baseline available" value={display(e.risk?.abnormality?.baseline_available)}/><p>{e.risk?.abnormality?.reason||'Baseline explanation unavailable.'}</p><details><summary>Reported history and feature values</summary><pre className="evidence-json">{JSON.stringify({history:e.history||null,features:e.features||null},null,2)}</pre></details></section>
 <section className="review-card"><h2>Deterministic risk</h2><RiskBadge level={e.risk?.risk_level}/><StatRow label="Risk score" value={display(e.risk?.risk_score)}/><p>Risk is calculated separately from ML classification. These are backend-reported factors; no frontend reweighting is applied.</p>{Object.entries(e.risk?.risk_factors||{}).map(([name,value])=><StatRow key={name} label={name.replaceAll('_',' ')} value={display(value)}/>)}<h3>Missing risk context</h3><p>{e.risk?.missing_context?.join(', ')||'None reported'}</p><h3>Read-only lifecycle</h3><p>Reported event status: {e.status||'Unavailable'}. New, Under Review, Confirmed, Monitoring, Escalating, Stable, Resolved and Archived are future workflow states; none is assigned from risk alone.</p></section>
 <section className="review-card"><h2>Environmental conditions</h2>{(['weather','air_quality'] as const).map(key=>{const p=e.context?.[key];const fields=key==='weather'?['temperature_c','relative_humidity_percent','wind_speed_kmh','wind_direction_deg','precipitation_mm']:['pm2_5','pm10','carbon_monoxide','nitrogen_dioxide','ozone'];return <section key={key}><h3>{key.replaceAll('_',' ')}</h3><p>{p?.provider||'Provider unavailable'} · {p?.status||'Unavailable'}</p><p>Fetched: {p?.fetched_at||'Unavailable'} ({freshness(p?.fetched_at)}) · Observation: {p?.observed_at||'Unavailable'}</p><p>{p?.reason||''}</p>{fields.map(field=><StatRow key={field} label={field.replaceAll('_',' ')} value={p?.status==='available'?display(p[field]):'Unavailable'}/>)}<small>{p?.attribution||'Attribution unavailable'} · {p?.units||'Use provider-reported units'}</small></section>})}<p>Wind describes downwind context, not predicted fire spread or plume dispersion.</p></section>
 <section className="review-card"><h2>Nearby industrial facilities</h2>{e.context?.osm_context_available&&e.context.nearby_facility_names?.length?<ul>{e.context.nearby_facility_names.map((name,i)=><li key={`${name}-${i}`}>{name} · type and individual distance unavailable</li>)}</ul>:<p>Facility list unavailable.</p>}<StatRow label="Distance to industrial context (m)" value={display(e.context?.distance_to_industrial_m)}/><p>Facility-linked recurrence, associated-event histories and known-source registries are not exposed. Event positions are not facility coordinates.</p></section>
 <section className="review-card"><h2>Recorded timeline</h2><ol className="event-timeline">{timeline(e,alerts,review).map((row,i)=><li key={`${row.at}-${i}`}><time>{row.at}</time><p>{row.label}</p></li>)}</ol><p>Intermediate detection, classification and risk-update timestamps require audit history. No timestamps are inferred.</p></section>
 <section className="review-card intelligence-wide"><h2>Event data lineage</h2><ol className="lineage-flow">{lineage(e,alerts,review).map(([stage,state])=><li key={stage}><b>{stage}</b><span>{state}</span></li>)}</ol></section></div>;
}
