'use client';
import {useState} from 'react';
import {apiPost, type ThermalEvent, type ProviderContext} from '../lib/api';
const titles:Record<string,string>={location:'Location',weather:'Weather',air_quality:'Air quality',eonet:'Natural hazard context',routing:'Road access'};
const fields:Record<string,string>={display_name:'Location',city:'City',district:'District',state:'State',country:'Country',temperature_c:'Temperature (°C)',relative_humidity_percent:'Relative humidity (%)',precipitation_mm:'Precipitation (mm)',wind_speed_kmh:'Wind speed (km/h)',wind_direction_deg:'Wind direction (°)',pm2_5:'PM2.5 (μg/m³)',pm10:'PM10 (μg/m³)',carbon_monoxide:'CO (μg/m³)',nitrogen_dioxide:'NO₂ (μg/m³)',ozone:'Ozone (μg/m³)',matched:'Nearby hazard match',event_id:'Hazard ID',title:'Hazard',category:'Category',distance_km:'Distance (km)',event_date:'Hazard date',observed_at:'Context hour (UTC)',distance_m:'Road distance (m)',duration_seconds:'Estimated driving time (s)'};
export default function ContextPanel({event,token,onRoute}:{event:ThermalEvent;token:string;onRoute:(packet:ProviderContext)=>void}){
 const [lat,setLat]=useState(''),[lon,setLon]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function route(){setBusy(true);setError('');try{onRoute(await apiPost<ProviderContext>('/events/'+encodeURIComponent(event.id)+'/route',{latitude:Number(lat),longitude:Number(lon)},token,65000))}catch(e){setError(e instanceof Error?e.message:'Route unavailable')}finally{setBusy(false)}}
 return <section><h3>External evidence</h3>{Object.entries(titles).map(([key,title])=>{const packet=event.context[key] as ProviderContext|undefined;const status=key==='routing'&&busy?'loading':packet?.status||'unavailable';return <details key={key} open={key==='location'}><summary>{title} · {status}</summary>{packet?.status==='available'?<><dl>{Object.entries(fields).filter(([field])=>field in packet).map(([field,label])=><div key={field}><dt>{label}</dt><dd>{packet[field]===null?'Not available':typeof packet[field]==='boolean'?(packet[field]?'Yes':'No'):String(packet[field])}</dd></div>)}</dl>{packet.refresh_status&&<p>Refresh {String(packet.refresh_status)}; showing earlier context from {String(packet.fetched_at)}.</p>}<p className="small">{String(packet.provider)} · Retrieved {String(packet.fetched_at)}{packet.attribution?' · '+String(packet.attribution):''}</p>{key==='eonet'&&<p className="small">Point hazards within 50 km and 72 hours; supporting context, not classification.</p>}{(key==='weather'||key==='air_quality')&&<p className="small">Modelled grid context for the event hour; not an on-site measurement.</p>}</>:<p>{String(packet?.reason||'Not enriched yet').replaceAll('_',' ')}</p>}</details>})}<details><summary>Route to a response point</summary><p className="small">Enter a known destination. Routing must be enabled on the backend. A road route does not confirm safe emergency access.</p><label>Destination latitude<input aria-label="Destination latitude" type="number" min="-90" max="90" step="any" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Destination longitude<input aria-label="Destination longitude" type="number" min="-180" max="180" step="any" value={lon} onChange={e=>setLon(e.target.value)}/></label><button className="button" type="button" disabled={busy||!lat||!lon||event.is_demo} onClick={route}>{busy?'Loading route…':'Find road route'}</button>{error&&<p role="alert">{error}</p>}</details></section>
}
