'use client';
import {useEffect,useState} from 'react';
import {apiGet,ApiError,type ModelStatus} from '../lib/api';
import {LoadingSkeleton,ErrorState,EmptyState,SectionHeader,StatRow} from './UI';

type Evaluation={rows?:number;accuracy?:number;balanced_accuracy?:number;macro_f1?:number;per_class?:Record<string,{precision?:number;recall?:number;'f1-score'?:number;support?:number}|number>;confusion_matrix?:number[][]};
type Metrics={available?:boolean;reason?:string;algorithm?:string;model_version?:string;feature_version?:string;training_rows?:number;classes?:string[];features?:string[];validation?:Evaluation;test?:Evaluation;split_counts?:Record<string,number>;split_groups?:Record<string,unknown>};
const percent=(n:unknown)=>typeof n==='number'&&Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'Unavailable';
export default function ModelView({token,model,onUnauthorized}:{token:string;model:ModelStatus|null;onUnauthorized:(error:unknown)=>void}){
 const [data,setData]=useState<Metrics|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');apiGet<Metrics>('/model/metrics',token).then(r=>{if(active)setData(r)}).catch(e=>{if(active){setError(e instanceof Error?e.message:'Model evaluation unavailable');if(e instanceof ApiError&&e.status===401)onUnauthorized(e)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[token,attempt]);
 return <div className="model-view"><SectionHeader title="Model evaluation" description="Recorded held-out evaluation. Metrics describe this dataset, not guaranteed field performance."/>
 <section className="review-card"><div className="model-status-grid"><StatRow label="Model available" value={model?model.model_available?'Yes':'No':'Unavailable'}/><StatRow label="Training ready" value={model?model.training_ready?'Yes':'No':'Unavailable'}/><StatRow label="Model version" value={model?.model_version||'Unavailable'}/><StatRow label="Feature version" value={model?.feature_version||'Unavailable'}/></div>{model?.reason&&<p>{model.reason}</p>}</section>
 {loading&&<LoadingSkeleton label="Loading model evaluation"/>}{error&&<ErrorState message={error} onRetry={()=>setAttempt(n=>n+1)}/>}{error&&data&&<p role="status">Previously loaded evaluation shown; refresh failed.</p>}
 {!loading&&!error&&(!data||data.available===false)&&<EmptyState title="No evaluated model" description={data?.reason||'Evaluation data is not yet available.'}/>}
 {data&&data.available!==false&&<><section className="review-card"><SectionHeader title={data.algorithm||'Algorithm unavailable'}/><StatRow label="Training rows" value={data.training_rows??'Unavailable'}/>{(data.training_rows??0)<100&&<p className="notice-banner">Small or unreported sample size. Treat these metrics as preliminary evidence.</p>}<div className="model-status-grid">{['train','validation','test'].map(split=><div key={split}><StatRow label={`${split} rows`} value={data.split_counts?.[split]??'Unavailable'}/><StatRow label={`${split} groups`} value={Array.isArray(data.split_groups?.[split])?(data.split_groups[split] as unknown[]).length:typeof data.split_groups?.[split]==='number'?String(data.split_groups[split]):'Unavailable'}/></div>)}</div></section>
 {(['validation','test'] as const).map(split=>{const evaluation=data[split];return <section className="review-card" key={split}><SectionHeader title={`${split==='test'?'Test':'Validation'} performance`}/>{!evaluation?<EmptyState description="This split has no recorded evaluation."/>:<><div className="model-status-grid"><StatRow label="Rows" value={evaluation.rows??'Unavailable'}/><StatRow label="Accuracy" value={percent(evaluation.accuracy)}/><StatRow label="Balanced accuracy" value={percent(evaluation.balanced_accuracy)}/><StatRow label="Macro F1" value={percent(evaluation.macro_f1)}/></div><div className="data-table-scroll" role="region" aria-label={`${split} class metrics`} tabIndex={0}><table className="data-table"><caption>Class performance</caption><thead><tr><th>Class</th><th>Precision</th><th>Recall</th><th>F1</th><th>Support</th></tr></thead><tbody>{(data.classes||[]).map(name=>{const row=evaluation.per_class?.[name];return <tr key={name}><th scope="row">{name.replaceAll('_',' ')}</th><td>{percent(typeof row==='object'?row.precision:null)}</td><td>{percent(typeof row==='object'?row.recall:null)}</td><td>{percent(typeof row==='object'?row['f1-score']:null)}</td><td>{typeof row==='object'?row.support??'Unavailable':'Unavailable'}</td></tr>})}</tbody></table></div>{evaluation.confusion_matrix&&data.classes?.length?<div className="data-table-scroll" role="region" aria-label={`${split} confusion matrix`} tabIndex={0}><table className="data-table confusion-matrix"><caption>Confusion matrix · rows: actual / columns: predicted</caption><thead><tr><th>Actual / predicted</th>{data.classes.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{data.classes.map((c,i)=><tr key={c}><th scope="row">{c.replaceAll('_',' ')}</th>{data.classes!.map((p,j)=><td key={p} className={i===j?'matrix-diagonal':''}>{evaluation.confusion_matrix?.[i]?.[j]??'Unavailable'}</td>)}</tr>)}</tbody></table></div>:<p>Confusion matrix unavailable.</p>}</>}</section>})}<section className="review-card"><details><summary>Model features ({data.features?.length??'unavailable'})</summary>{data.features?.length?<ul className="feature-list">{data.features.map(f=><li key={f}>{f.replaceAll('_',' ')}</li>)}</ul>:<p>Feature list unavailable.</p>}</details></section></>}
 </div>;
}
